// GENERATED by scripts/build-pieces.py from third_party/cburnett (BSD-3-Clause, Colin M.L. Burnett).
// Do not edit: change the SVGs or the script and rerun it.
@file:Suppress("MagicNumber")

package com.yarosz.chess.board

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.yarosz.chess.rules.Piece

/** The cburnett piece set as ImageVectors on a 45 × 45 viewport, built once per piece on first use. */
internal object CburnettPieces {

    private val cache = arrayOfNulls<ImageVector>(Piece.entries.size)

    fun vector(piece: Piece): ImageVector =
        cache[piece.ordinal] ?: build(piece).also { cache[piece.ordinal] = it }

    private fun build(piece: Piece): ImageVector = when (piece) {
        Piece.WHITE_PAWN -> whitePawn()
        Piece.WHITE_KNIGHT -> whiteKnight()
        Piece.WHITE_BISHOP -> whiteBishop()
        Piece.WHITE_ROOK -> whiteRook()
        Piece.WHITE_QUEEN -> whiteQueen()
        Piece.WHITE_KING -> whiteKing()
        Piece.BLACK_PAWN -> blackPawn()
        Piece.BLACK_KNIGHT -> blackKnight()
        Piece.BLACK_BISHOP -> blackBishop()
        Piece.BLACK_ROOK -> blackRook()
        Piece.BLACK_QUEEN -> blackQueen()
        Piece.BLACK_KING -> blackKing()
    }

    private inline fun piece(name: String, paths: ImageVector.Builder.() -> Unit): ImageVector =
        ImageVector.Builder(name = name, defaultWidth = 45.dp, defaultHeight = 45.dp, viewportWidth = 45f, viewportHeight = 45f)
            .apply(paths)
            .build()

    private fun whitePawn(): ImageVector = piece("WHITE_PAWN") {
        // Chess_plt45.svg
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.NonZero) {
            moveTo(22.5f, 9f)
            curveTo(20.29f, 9f, 18.5f, 10.79f, 18.5f, 13f)
            curveTo(18.5f, 13.89f, 18.79f, 14.71f, 19.28f, 15.38f)
            curveTo(17.33f, 16.5f, 16f, 18.59f, 16f, 21f)
            curveTo(16f, 23.03f, 16.94f, 24.84f, 18.41f, 26.03f)
            curveTo(15.41f, 27.09f, 11f, 31.58f, 11f, 39.5f)
            lineTo(34f, 39.5f)
            curveTo(34f, 31.58f, 29.59f, 27.09f, 26.59f, 26.03f)
            curveTo(28.06f, 24.84f, 29f, 23.03f, 29f, 21f)
            curveTo(29f, 18.59f, 27.67f, 16.5f, 25.72f, 15.38f)
            curveTo(26.21f, 14.71f, 26.5f, 13.89f, 26.5f, 13f)
            curveTo(26.5f, 10.79f, 24.71f, 9f, 22.5f, 9f)
            close()
        }
    }

    private fun whiteKnight(): ImageVector = piece("WHITE_KNIGHT") {
        // Chess_nlt45.svg
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(22f, 10.3f)
            curveTo(32.5f, 11.3f, 38.5f, 18.3f, 38f, 39.3f)
            lineTo(15f, 39.3f)
            curveTo(15f, 30.3f, 25f, 32.8f, 23f, 18.3f)
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(24f, 18.3f)
            curveTo(24.38f, 21.21f, 18.45f, 25.67f, 16f, 27.3f)
            curveTo(13f, 29.3f, 13.18f, 31.64f, 11f, 31.3f)
            curveTo(9.958f, 30.36f, 12.41f, 28.26f, 11f, 28.3f)
            curveTo(10f, 28.3f, 11.19f, 29.53f, 10f, 30.3f)
            curveTo(9f, 30.3f, 5.997f, 31.3f, 6f, 26.3f)
            curveTo(6f, 24.3f, 12f, 14.3f, 12f, 14.3f)
            curveTo(12f, 14.3f, 13.89f, 12.4f, 14f, 10.8f)
            curveTo(13.27f, 9.806f, 13.5f, 8.8f, 13.5f, 7.8f)
            curveTo(14.5f, 6.8f, 16.5f, 10.3f, 16.5f, 10.3f)
            lineTo(18.5f, 10.3f)
            curveTo(18.5f, 10.3f, 19.28f, 8.308f, 21f, 7.3f)
            curveTo(22f, 7.3f, 22f, 10.3f, 22f, 10.3f)
        }
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(9.5f, 25.8f)
            curveTo(9.5f, 26.076f, 9.276f, 26.3f, 9f, 26.3f)
            curveTo(8.724f, 26.3f, 8.5f, 26.076f, 8.5f, 25.8f)
            curveTo(8.5f, 25.524f, 8.724f, 25.3f, 9f, 25.3f)
            curveTo(9.276f, 25.3f, 9.5f, 25.524f, 9.5f, 25.8f)
            close()
        }
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(14.933f, 16.05f)
            curveTo(14.519f, 16.767f, 13.989f, 17.237f, 13.75f, 17.099f)
            curveTo(13.511f, 16.961f, 13.653f, 16.267f, 14.067f, 15.55f)
            curveTo(14.481f, 14.833f, 15.011f, 14.363f, 15.25f, 14.501f)
            curveTo(15.489f, 14.639f, 15.347f, 15.333f, 14.933f, 16.05f)
            close()
        }
    }

    private fun whiteBishop(): ImageVector = piece("WHITE_BISHOP") {
        // Chess_blt45.svg
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(9f, 36.6f)
            curveTo(12.39f, 35.63f, 19.11f, 37.03f, 22.5f, 34.6f)
            curveTo(25.89f, 37.03f, 32.61f, 35.63f, 36f, 36.6f)
            curveTo(36f, 36.6f, 37.65f, 37.14f, 39f, 38.6f)
            curveTo(38.32f, 39.57f, 37.35f, 39.59f, 36f, 39.1f)
            curveTo(32.61f, 38.13f, 25.89f, 39.56f, 22.5f, 38.1f)
            curveTo(19.11f, 39.56f, 12.39f, 38.13f, 9f, 39.1f)
            curveTo(7.65f, 39.59f, 6.68f, 39.57f, 6f, 38.6f)
            curveTo(7.35f, 37.14f, 9f, 36.6f, 9f, 36.6f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(15f, 32.6f)
            curveTo(17.5f, 35.1f, 27.5f, 35.1f, 30f, 32.6f)
            curveTo(30.5f, 31.1f, 30f, 30.6f, 30f, 30.6f)
            curveTo(30f, 28.1f, 27.5f, 26.6f, 27.5f, 26.6f)
            curveTo(33f, 25.1f, 33.5f, 15.1f, 22.5f, 11.1f)
            curveTo(11.5f, 15.1f, 12f, 25.1f, 17.5f, 26.6f)
            curveTo(17.5f, 26.6f, 15f, 28.1f, 15f, 30.6f)
            curveTo(15f, 30.6f, 14.5f, 31.1f, 15f, 32.6f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(25f, 8.6f)
            curveTo(25f, 9.981f, 23.881f, 11.1f, 22.5f, 11.1f)
            curveTo(21.119f, 11.1f, 20f, 9.981f, 20f, 8.6f)
            curveTo(20f, 7.219f, 21.119f, 6.1f, 22.5f, 6.1f)
            curveTo(23.881f, 6.1f, 25f, 7.219f, 25f, 8.6f)
            close()
        }
        path(fill = null, stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.EvenOdd) {
            moveTo(17.5f, 26.6f)
            lineTo(27.5f, 26.6f)
            moveTo(15f, 30.6f)
            lineTo(30f, 30.6f)
            moveTo(22.5f, 16.1f)
            lineTo(22.5f, 21.1f)
            moveTo(20f, 18.6f)
            lineTo(25f, 18.6f)
        }
    }

    private fun whiteRook(): ImageVector = piece("WHITE_ROOK") {
        // Chess_rlt45.svg
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(9f, 39.3f)
            lineTo(36f, 39.3f)
            lineTo(36f, 36.3f)
            lineTo(9f, 36.3f)
            lineTo(9f, 39.3f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(12f, 36.3f)
            lineTo(12f, 32.3f)
            lineTo(33f, 32.3f)
            lineTo(33f, 36.3f)
            lineTo(12f, 36.3f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(11f, 14.3f)
            lineTo(11f, 9.3f)
            lineTo(15f, 9.3f)
            lineTo(15f, 11.3f)
            lineTo(20f, 11.3f)
            lineTo(20f, 9.3f)
            lineTo(25f, 9.3f)
            lineTo(25f, 11.3f)
            lineTo(30f, 11.3f)
            lineTo(30f, 9.3f)
            lineTo(34f, 9.3f)
            lineTo(34f, 14.3f)
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(34f, 14.3f)
            lineTo(31f, 17.3f)
            lineTo(14f, 17.3f)
            lineTo(11f, 14.3f)
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.EvenOdd) {
            moveTo(31f, 17.3f)
            lineTo(31f, 29.8f)
            lineTo(14f, 29.8f)
            lineTo(14f, 17.3f)
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(31f, 29.8f)
            lineTo(32.5f, 32.3f)
            lineTo(12.5f, 32.3f)
            lineTo(14f, 29.8f)
        }
        path(fill = null, stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.EvenOdd) {
            moveTo(11f, 14.3f)
            lineTo(34f, 14.3f)
        }
    }

    private fun whiteQueen(): ImageVector = piece("WHITE_QUEEN") {
        // Chess_qlt45.svg
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(9f, 26f)
            curveTo(17.5f, 24.5f, 30f, 24.5f, 36f, 26f)
            lineTo(38.5f, 13.5f)
            lineTo(31f, 25f)
            lineTo(30.7f, 10.9f)
            lineTo(25.5f, 24.5f)
            lineTo(22.5f, 10f)
            lineTo(19.5f, 24.5f)
            lineTo(14.3f, 10.9f)
            lineTo(14f, 25f)
            lineTo(6.5f, 13.5f)
            lineTo(9f, 26f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(9f, 26f)
            curveTo(9f, 28f, 10.5f, 28f, 11.5f, 30f)
            curveTo(12.5f, 31.5f, 12.5f, 31f, 12f, 33.5f)
            curveTo(10.5f, 34.5f, 11f, 36f, 11f, 36f)
            curveTo(9.5f, 37.5f, 11f, 38.5f, 11f, 38.5f)
            curveTo(17.5f, 39.5f, 27.5f, 39.5f, 34f, 38.5f)
            curveTo(34f, 38.5f, 35.5f, 37.5f, 34f, 36f)
            curveTo(34f, 36f, 34.5f, 34.5f, 33f, 33.5f)
            curveTo(32.5f, 31f, 32.5f, 31.5f, 33.5f, 30f)
            curveTo(34.5f, 28f, 36f, 28f, 36f, 26f)
            curveTo(27.5f, 24.5f, 17.5f, 24.5f, 9f, 26f)
            close()
        }
        path(fill = null, stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(11.5f, 30f)
            curveTo(15f, 29f, 30f, 29f, 33.5f, 30f)
        }
        path(fill = null, stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(12f, 33.5f)
            curveTo(18f, 32.5f, 27f, 32.5f, 33f, 33.5f)
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(8f, 12f)
            curveTo(8f, 13.105f, 7.105f, 14f, 6f, 14f)
            curveTo(4.895f, 14f, 4f, 13.105f, 4f, 12f)
            curveTo(4f, 10.895f, 4.895f, 10f, 6f, 10f)
            curveTo(7.105f, 10f, 8f, 10.895f, 8f, 12f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(16f, 9f)
            curveTo(16f, 10.105f, 15.105f, 11f, 14f, 11f)
            curveTo(12.895f, 11f, 12f, 10.105f, 12f, 9f)
            curveTo(12f, 7.895f, 12.895f, 7f, 14f, 7f)
            curveTo(15.105f, 7f, 16f, 7.895f, 16f, 9f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(24.5f, 8f)
            curveTo(24.5f, 9.105f, 23.605f, 10f, 22.5f, 10f)
            curveTo(21.395f, 10f, 20.5f, 9.105f, 20.5f, 8f)
            curveTo(20.5f, 6.895f, 21.395f, 6f, 22.5f, 6f)
            curveTo(23.605f, 6f, 24.5f, 6.895f, 24.5f, 8f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(33f, 9f)
            curveTo(33f, 10.105f, 32.105f, 11f, 31f, 11f)
            curveTo(29.895f, 11f, 29f, 10.105f, 29f, 9f)
            curveTo(29f, 7.895f, 29.895f, 7f, 31f, 7f)
            curveTo(32.105f, 7f, 33f, 7.895f, 33f, 9f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(41f, 12f)
            curveTo(41f, 13.105f, 40.105f, 14f, 39f, 14f)
            curveTo(37.895f, 14f, 37f, 13.105f, 37f, 12f)
            curveTo(37f, 10.895f, 37.895f, 10f, 39f, 10f)
            curveTo(40.105f, 10f, 41f, 10.895f, 41f, 12f)
            close()
        }
    }

    private fun whiteKing(): ImageVector = piece("WHITE_KING") {
        // Chess_klt45.svg
        path(fill = null, stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.EvenOdd) {
            moveTo(22.5f, 11.63f)
            lineTo(22.5f, 6f)
            moveTo(20f, 8f)
            lineTo(25f, 8f)
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.EvenOdd) {
            moveTo(22.5f, 25f)
            curveTo(22.5f, 25f, 27f, 17.5f, 25.5f, 14.5f)
            curveTo(25.5f, 14.5f, 24.5f, 12f, 22.5f, 12f)
            curveTo(20.5f, 12f, 19.5f, 14.5f, 19.5f, 14.5f)
            curveTo(18f, 17.5f, 22.5f, 25f, 22.5f, 25f)
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(12.5f, 37f)
            curveTo(18f, 40.5f, 27f, 40.5f, 32.5f, 37f)
            lineTo(32.5f, 30f)
            curveTo(32.5f, 30f, 41.5f, 25.5f, 38.5f, 19.5f)
            curveTo(34.5f, 13f, 25f, 16f, 22.5f, 23.5f)
            lineTo(22.5f, 27f)
            lineTo(22.5f, 23.5f)
            curveTo(20f, 16f, 10.5f, 13f, 6.5f, 19.5f)
            curveTo(3.5f, 25.5f, 12.5f, 30f, 12.5f, 30f)
            lineTo(12.5f, 37f)
        }
        path(fill = null, stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(12.5f, 30f)
            curveTo(18f, 27f, 27f, 27f, 32.5f, 30f)
            moveTo(12.5f, 33.5f)
            curveTo(18f, 30.5f, 27f, 30.5f, 32.5f, 33.5f)
            moveTo(12.5f, 37f)
            curveTo(18f, 34f, 27f, 34f, 32.5f, 37f)
        }
    }

    private fun blackPawn(): ImageVector = piece("BLACK_PAWN") {
        // Chess_pdt45.svg
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.NonZero) {
            moveTo(22.5f, 9f)
            curveTo(20.29f, 9f, 18.5f, 10.79f, 18.5f, 13f)
            curveTo(18.5f, 13.89f, 18.79f, 14.71f, 19.28f, 15.38f)
            curveTo(17.33f, 16.5f, 16f, 18.59f, 16f, 21f)
            curveTo(16f, 23.03f, 16.94f, 24.84f, 18.41f, 26.03f)
            curveTo(15.41f, 27.09f, 11f, 31.58f, 11f, 39.5f)
            lineTo(34f, 39.5f)
            curveTo(34f, 31.58f, 29.59f, 27.09f, 26.59f, 26.03f)
            curveTo(28.06f, 24.84f, 29f, 23.03f, 29f, 21f)
            curveTo(29f, 18.59f, 27.67f, 16.5f, 25.72f, 15.38f)
            curveTo(26.21f, 14.71f, 26.5f, 13.89f, 26.5f, 13f)
            curveTo(26.5f, 10.79f, 24.71f, 9f, 22.5f, 9f)
            close()
        }
    }

    private fun blackKnight(): ImageVector = piece("BLACK_KNIGHT") {
        // Chess_ndt45.svg
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(22f, 10.3f)
            curveTo(32.5f, 11.3f, 38.5f, 18.3f, 38f, 39.3f)
            lineTo(15f, 39.3f)
            curveTo(15f, 30.3f, 25f, 32.8f, 23f, 18.3f)
        }
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(24f, 18.3f)
            curveTo(24.38f, 21.21f, 18.45f, 25.67f, 16f, 27.3f)
            curveTo(13f, 29.3f, 13.18f, 31.64f, 11f, 31.3f)
            curveTo(9.958f, 30.36f, 12.41f, 28.26f, 11f, 28.3f)
            curveTo(10f, 28.3f, 11.19f, 29.53f, 10f, 30.3f)
            curveTo(9f, 30.3f, 5.997f, 31.3f, 6f, 26.3f)
            curveTo(6f, 24.3f, 12f, 14.3f, 12f, 14.3f)
            curveTo(12f, 14.3f, 13.89f, 12.4f, 14f, 10.8f)
            curveTo(13.27f, 9.806f, 13.5f, 8.8f, 13.5f, 7.8f)
            curveTo(14.5f, 6.8f, 16.5f, 10.3f, 16.5f, 10.3f)
            lineTo(18.5f, 10.3f)
            curveTo(18.5f, 10.3f, 19.28f, 8.308f, 21f, 7.3f)
            curveTo(22f, 7.3f, 22f, 10.3f, 22f, 10.3f)
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFFFFFFFF)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(9.5f, 25.8f)
            curveTo(9.5f, 26.076f, 9.276f, 26.3f, 9f, 26.3f)
            curveTo(8.724f, 26.3f, 8.5f, 26.076f, 8.5f, 25.8f)
            curveTo(8.5f, 25.524f, 8.724f, 25.3f, 9f, 25.3f)
            curveTo(9.276f, 25.3f, 9.5f, 25.524f, 9.5f, 25.8f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFFFFFFFF)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(14.933f, 16.05f)
            curveTo(14.519f, 16.767f, 13.989f, 17.237f, 13.75f, 17.099f)
            curveTo(13.511f, 16.961f, 13.653f, 16.267f, 14.067f, 15.55f)
            curveTo(14.481f, 14.833f, 15.011f, 14.363f, 15.25f, 14.501f)
            curveTo(15.489f, 14.639f, 15.347f, 15.333f, 14.933f, 16.05f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = null, strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(24.55f, 10.7f)
            lineTo(24.1f, 12.15f)
            lineTo(24.6f, 12.3f)
            curveTo(27.75f, 13.3f, 30.25f, 14.79f, 32.5f, 19.05f)
            curveTo(34.75f, 23.31f, 35.75f, 29.36f, 35.25f, 39.3f)
            lineTo(35.2f, 39.8f)
            lineTo(37.45f, 39.8f)
            lineTo(37.5f, 39.3f)
            curveTo(38f, 29.24f, 36.62f, 22.45f, 34.25f, 17.96f)
            curveTo(31.88f, 13.47f, 28.46f, 11.32f, 25.06f, 10.8f)
            lineTo(24.55f, 10.7f)
            close()
        }
    }

    private fun blackBishop(): ImageVector = piece("BLACK_BISHOP") {
        // Chess_bdt45.svg
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(9f, 36.6f)
            curveTo(12.39f, 35.63f, 19.11f, 37.03f, 22.5f, 34.6f)
            curveTo(25.89f, 37.03f, 32.61f, 35.63f, 36f, 36.6f)
            curveTo(36f, 36.6f, 37.65f, 37.14f, 39f, 38.6f)
            curveTo(38.32f, 39.57f, 37.35f, 39.59f, 36f, 39.1f)
            curveTo(32.61f, 38.13f, 25.89f, 39.56f, 22.5f, 38.1f)
            curveTo(19.11f, 39.56f, 12.39f, 38.13f, 9f, 39.1f)
            curveTo(7.65f, 39.59f, 6.68f, 39.57f, 6f, 38.6f)
            curveTo(7.35f, 37.14f, 9f, 36.6f, 9f, 36.6f)
            close()
        }
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(15f, 32.6f)
            curveTo(17.5f, 35.1f, 27.5f, 35.1f, 30f, 32.6f)
            curveTo(30.5f, 31.1f, 30f, 30.6f, 30f, 30.6f)
            curveTo(30f, 28.1f, 27.5f, 26.6f, 27.5f, 26.6f)
            curveTo(33f, 25.1f, 33.5f, 15.1f, 22.5f, 11.1f)
            curveTo(11.5f, 15.1f, 12f, 25.1f, 17.5f, 26.6f)
            curveTo(17.5f, 26.6f, 15f, 28.1f, 15f, 30.6f)
            curveTo(15f, 30.6f, 14.5f, 31.1f, 15f, 32.6f)
            close()
        }
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(25f, 8.6f)
            curveTo(25f, 9.981f, 23.881f, 11.1f, 22.5f, 11.1f)
            curveTo(21.119f, 11.1f, 20f, 9.981f, 20f, 8.6f)
            curveTo(20f, 7.219f, 21.119f, 6.1f, 22.5f, 6.1f)
            curveTo(23.881f, 6.1f, 25f, 7.219f, 25f, 8.6f)
            close()
        }
        path(fill = null, stroke = SolidColor(Color(0xFFFFFFFF)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.EvenOdd) {
            moveTo(17.5f, 26.6f)
            lineTo(27.5f, 26.6f)
            moveTo(15f, 30.6f)
            lineTo(30f, 30.6f)
            moveTo(22.5f, 16.1f)
            lineTo(22.5f, 21.1f)
            moveTo(20f, 18.6f)
            lineTo(25f, 18.6f)
        }
    }

    private fun blackRook(): ImageVector = piece("BLACK_ROOK") {
        // Chess_rdt45.svg
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(9f, 39.3f)
            lineTo(36f, 39.3f)
            lineTo(36f, 36.3f)
            lineTo(9f, 36.3f)
            lineTo(9f, 39.3f)
            close()
        }
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(12.5f, 32.3f)
            lineTo(14f, 29.8f)
            lineTo(31f, 29.8f)
            lineTo(32.5f, 32.3f)
            lineTo(12.5f, 32.3f)
            close()
        }
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(12f, 36.3f)
            lineTo(12f, 32.3f)
            lineTo(33f, 32.3f)
            lineTo(33f, 36.3f)
            lineTo(12f, 36.3f)
            close()
        }
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.EvenOdd) {
            moveTo(14f, 29.8f)
            lineTo(14f, 16.8f)
            lineTo(31f, 16.8f)
            lineTo(31f, 29.8f)
            lineTo(14f, 29.8f)
            close()
        }
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(14f, 16.8f)
            lineTo(11f, 14.3f)
            lineTo(34f, 14.3f)
            lineTo(31f, 16.8f)
            lineTo(14f, 16.8f)
            close()
        }
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(11f, 14.3f)
            lineTo(11f, 9.3f)
            lineTo(15f, 9.3f)
            lineTo(15f, 11.3f)
            lineTo(20f, 11.3f)
            lineTo(20f, 9.3f)
            lineTo(25f, 9.3f)
            lineTo(25f, 11.3f)
            lineTo(30f, 11.3f)
            lineTo(30f, 9.3f)
            lineTo(34f, 9.3f)
            lineTo(34f, 14.3f)
            lineTo(11f, 14.3f)
            close()
        }
        path(fill = null, stroke = SolidColor(Color(0xFFFFFFFF)), strokeLineWidth = 1f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.EvenOdd) {
            moveTo(12f, 35.8f)
            lineTo(33f, 35.8f)
            lineTo(33f, 35.8f)
        }
        path(fill = null, stroke = SolidColor(Color(0xFFFFFFFF)), strokeLineWidth = 1f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.EvenOdd) {
            moveTo(13f, 31.8f)
            lineTo(32f, 31.8f)
        }
        path(fill = null, stroke = SolidColor(Color(0xFFFFFFFF)), strokeLineWidth = 1f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.EvenOdd) {
            moveTo(14f, 29.8f)
            lineTo(31f, 29.8f)
        }
        path(fill = null, stroke = SolidColor(Color(0xFFFFFFFF)), strokeLineWidth = 1f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.EvenOdd) {
            moveTo(14f, 16.8f)
            lineTo(31f, 16.8f)
        }
        path(fill = null, stroke = SolidColor(Color(0xFFFFFFFF)), strokeLineWidth = 1f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.EvenOdd) {
            moveTo(11f, 14.3f)
            lineTo(34f, 14.3f)
        }
    }

    private fun blackQueen(): ImageVector = piece("BLACK_QUEEN") {
        // Chess_qdt45.svg
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(9f, 26f)
            curveTo(17.5f, 24.5f, 30f, 24.5f, 36f, 26f)
            lineTo(38.5f, 13.5f)
            lineTo(31f, 25f)
            lineTo(30.7f, 10.9f)
            lineTo(25.5f, 24.5f)
            lineTo(22.5f, 10f)
            lineTo(19.5f, 24.5f)
            lineTo(14.3f, 10.9f)
            lineTo(14f, 25f)
            lineTo(6.5f, 13.5f)
            lineTo(9f, 26f)
            close()
        }
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(9f, 26f)
            curveTo(9f, 28f, 10.5f, 28f, 11.5f, 30f)
            curveTo(12.5f, 31.5f, 12.5f, 31f, 12f, 33.5f)
            curveTo(10.5f, 34.5f, 11f, 36f, 11f, 36f)
            curveTo(9.5f, 37.5f, 11f, 38.5f, 11f, 38.5f)
            curveTo(17.5f, 39.5f, 27.5f, 39.5f, 34f, 38.5f)
            curveTo(34f, 38.5f, 35.5f, 37.5f, 34f, 36f)
            curveTo(34f, 36f, 34.5f, 34.5f, 33f, 33.5f)
            curveTo(32.5f, 31f, 32.5f, 31.5f, 33.5f, 30f)
            curveTo(34.5f, 28f, 36f, 28f, 36f, 26f)
            curveTo(27.5f, 24.5f, 17.5f, 24.5f, 9f, 26f)
            close()
        }
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(11.5f, 30f)
            curveTo(15f, 29f, 30f, 29f, 33.5f, 30f)
        }
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(12f, 33.5f)
            curveTo(18f, 32.5f, 27f, 32.5f, 33f, 33.5f)
        }
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(8f, 12f)
            curveTo(8f, 13.105f, 7.105f, 14f, 6f, 14f)
            curveTo(4.895f, 14f, 4f, 13.105f, 4f, 12f)
            curveTo(4f, 10.895f, 4.895f, 10f, 6f, 10f)
            curveTo(7.105f, 10f, 8f, 10.895f, 8f, 12f)
            close()
        }
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(16f, 9f)
            curveTo(16f, 10.105f, 15.105f, 11f, 14f, 11f)
            curveTo(12.895f, 11f, 12f, 10.105f, 12f, 9f)
            curveTo(12f, 7.895f, 12.895f, 7f, 14f, 7f)
            curveTo(15.105f, 7f, 16f, 7.895f, 16f, 9f)
            close()
        }
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(24.5f, 8f)
            curveTo(24.5f, 9.105f, 23.605f, 10f, 22.5f, 10f)
            curveTo(21.395f, 10f, 20.5f, 9.105f, 20.5f, 8f)
            curveTo(20.5f, 6.895f, 21.395f, 6f, 22.5f, 6f)
            curveTo(23.605f, 6f, 24.5f, 6.895f, 24.5f, 8f)
            close()
        }
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(33f, 9f)
            curveTo(33f, 10.105f, 32.105f, 11f, 31f, 11f)
            curveTo(29.895f, 11f, 29f, 10.105f, 29f, 9f)
            curveTo(29f, 7.895f, 29.895f, 7f, 31f, 7f)
            curveTo(32.105f, 7f, 33f, 7.895f, 33f, 9f)
            close()
        }
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(41f, 12f)
            curveTo(41f, 13.105f, 40.105f, 14f, 39f, 14f)
            curveTo(37.895f, 14f, 37f, 13.105f, 37f, 12f)
            curveTo(37f, 10.895f, 37.895f, 10f, 39f, 10f)
            curveTo(40.105f, 10f, 41f, 10.895f, 41f, 12f)
            close()
        }
        path(fill = null, stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(11f, 38.5f)
            curveTo(18.448f, 41.091f, 26.552f, 41.091f, 34f, 38.5f)
        }
        path(fill = null, stroke = SolidColor(Color(0xFFFFFFFF)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(11f, 29f)
            curveTo(18.448f, 26.409f, 26.552f, 26.409f, 34f, 29f)
        }
        path(fill = null, stroke = SolidColor(Color(0xFFFFFFFF)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(12.5f, 31.5f)
            lineTo(32.5f, 31.5f)
        }
        path(fill = null, stroke = SolidColor(Color(0xFFFFFFFF)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(11.5f, 34.5f)
            curveTo(18.643f, 36.865f, 26.357f, 36.865f, 33.5f, 34.5f)
        }
        path(fill = null, stroke = SolidColor(Color(0xFFFFFFFF)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(10.5f, 37.5f)
            curveTo(18.25f, 40.329f, 26.75f, 40.329f, 34.5f, 37.5f)
        }
    }

    private fun blackKing(): ImageVector = piece("BLACK_KING") {
        // Chess_kdt45.svg
        path(fill = null, stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.EvenOdd) {
            moveTo(22.5f, 11.63f)
            lineTo(22.5f, 6f)
        }
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.EvenOdd) {
            moveTo(22.5f, 25f)
            curveTo(22.5f, 25f, 27f, 17.5f, 25.5f, 14.5f)
            curveTo(25.5f, 14.5f, 24.5f, 12f, 22.5f, 12f)
            curveTo(20.5f, 12f, 19.5f, 14.5f, 19.5f, 14.5f)
            curveTo(18f, 17.5f, 22.5f, 25f, 22.5f, 25f)
        }
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(12.5f, 37f)
            curveTo(18f, 40.5f, 27f, 40.5f, 32.5f, 37f)
            lineTo(32.5f, 30f)
            curveTo(32.5f, 30f, 41.5f, 25.5f, 38.5f, 19.5f)
            curveTo(34.5f, 13f, 25f, 16f, 22.5f, 23.5f)
            lineTo(22.5f, 27f)
            lineTo(22.5f, 23.5f)
            curveTo(20f, 16f, 10.5f, 13f, 6.5f, 19.5f)
            curveTo(3.5f, 25.5f, 12.5f, 30f, 12.5f, 30f)
            lineTo(12.5f, 37f)
        }
        path(fill = null, stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.EvenOdd) {
            moveTo(20f, 8f)
            lineTo(25f, 8f)
        }
        path(fill = null, stroke = SolidColor(Color(0xFFFFFFFF)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(32f, 29.5f)
            curveTo(32f, 29.5f, 40.5f, 25.5f, 38.03f, 19.85f)
            curveTo(34.15f, 14f, 25f, 18f, 22.5f, 24.5f)
            lineTo(22.5f, 26.6f)
            lineTo(22.5f, 24.5f)
            curveTo(20f, 18f, 10.85f, 14f, 6.97f, 19.85f)
            curveTo(4.5f, 25.5f, 13f, 29.5f, 13f, 29.5f)
        }
        path(fill = null, stroke = SolidColor(Color(0xFFFFFFFF)), strokeLineWidth = 1.5f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.EvenOdd) {
            moveTo(12.5f, 30f)
            curveTo(18f, 27f, 27f, 27f, 32.5f, 30f)
            moveTo(12.5f, 33.5f)
            curveTo(18f, 30.5f, 27f, 30.5f, 32.5f, 33.5f)
            moveTo(12.5f, 37f)
            curveTo(18f, 34f, 27f, 34f, 32.5f, 37f)
        }
    }
}
