// GENERATED by scripts/build-pieces.py from art/pieces (original drawings, CC0 1.0).
// Do not edit: change the SVGs or the script and rerun it.
@file:Suppress("MagicNumber")

package com.yarosz.chess.board

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.yarosz.chess.rules.Piece

/** The piece set (P1) as ImageVectors on a 45 × 45 viewport, built once per piece on first use. */
internal object PieceVectors {

    private val cache = arrayOfNulls<ImageVector>(Piece.entries.size)

    fun vector(piece: Piece): ImageVector =
        cache[piece.ordinal] ?: build(piece).also { cache[piece.ordinal] = it }

    private fun build(piece: Piece): ImageVector = when (piece) {
        Piece.WHITE_PAWN -> whitePawn()
        Piece.WHITE_KNIGHT -> whiteKnight()
        Piece.WHITE_BISHOP -> whiteBishop()
        Piece.WHITE_ROOK -> whiteRook()
        Piece.WHITE_QUEEN -> whiteQueen()
        Piece.WHITE_KING -> whiteKing()
        Piece.BLACK_PAWN -> blackPawn()
        Piece.BLACK_KNIGHT -> blackKnight()
        Piece.BLACK_BISHOP -> blackBishop()
        Piece.BLACK_ROOK -> blackRook()
        Piece.BLACK_QUEEN -> blackQueen()
        Piece.BLACK_KING -> blackKing()
    }

    private inline fun piece(name: String, paths: ImageVector.Builder.() -> Unit): ImageVector =
        ImageVector.Builder(name = name, defaultWidth = 45.dp, defaultHeight = 45.dp, viewportWidth = 45f, viewportHeight = 45f)
            .apply(paths)
            .build()

    private fun whitePawn(): ImageVector = piece("WHITE_PAWN") {
        // wP.svg
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 7.06f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(19.35f, 22.45f)
            curveTo(17.445f, 21.082f, 16.641f, 18.641f, 17.36f, 16.409f)
            curveTo(18.078f, 14.177f, 20.155f, 12.664f, 22.5f, 12.664f)
            curveTo(24.845f, 12.664f, 26.922f, 14.177f, 27.64f, 16.409f)
            curveTo(28.359f, 18.641f, 27.555f, 21.082f, 25.65f, 22.45f)
            lineTo(30.6f, 35.17f)
            lineTo(14.4f, 35.17f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFFFFFFFF)), strokeLineWidth = 3.06f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(19.35f, 22.45f)
            curveTo(17.445f, 21.082f, 16.641f, 18.641f, 17.36f, 16.409f)
            curveTo(18.078f, 14.177f, 20.155f, 12.664f, 22.5f, 12.664f)
            curveTo(24.845f, 12.664f, 26.922f, 14.177f, 27.64f, 16.409f)
            curveTo(28.359f, 18.641f, 27.555f, 21.082f, 25.65f, 22.45f)
            lineTo(30.6f, 35.17f)
            lineTo(14.4f, 35.17f)
            close()
        }
    }

    private fun whiteKnight(): ImageVector = piece("WHITE_KNIGHT") {
        // wN.svg
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 7.06f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(15.75f, 35.17f)
            lineTo(19.8f, 26.17f)
            lineTo(12.15f, 23.92f)
            lineTo(13.05f, 18.07f)
            lineTo(19.8f, 11.32f)
            lineTo(21.15f, 6.82f)
            lineTo(24.75f, 10.42f)
            lineTo(29.7f, 14.92f)
            lineTo(31.5f, 22.57f)
            lineTo(31.5f, 35.17f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFFFFFFFF)), strokeLineWidth = 3.06f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(15.75f, 35.17f)
            lineTo(19.8f, 26.17f)
            lineTo(12.15f, 23.92f)
            lineTo(13.05f, 18.07f)
            lineTo(19.8f, 11.32f)
            lineTo(21.15f, 6.82f)
            lineTo(24.75f, 10.42f)
            lineTo(29.7f, 14.92f)
            lineTo(31.5f, 22.57f)
            lineTo(31.5f, 35.17f)
            close()
        }
        path(fill = SolidColor(Color(0xFF000000)), stroke = null, strokeLineWidth = 1f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.NonZero) {
            moveTo(18.36f, 16.27f)
            curveTo(18.36f, 16.784f, 18.634f, 17.26f, 19.08f, 17.517f)
            curveTo(19.526f, 17.774f, 20.074f, 17.774f, 20.52f, 17.517f)
            curveTo(20.966f, 17.26f, 21.24f, 16.784f, 21.24f, 16.27f)
            curveTo(21.24f, 15.756f, 20.966f, 15.28f, 20.52f, 15.023f)
            curveTo(20.074f, 14.766f, 19.526f, 14.766f, 19.08f, 15.023f)
            curveTo(18.634f, 15.28f, 18.36f, 15.756f, 18.36f, 16.27f)
            close()
        }
    }

    private fun whiteBishop(): ImageVector = piece("WHITE_BISHOP") {
        // wB.svg
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 7.06f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(22.5f, 8.17f)
            lineTo(27.9f, 16.27f)
            lineTo(26.55f, 27.97f)
            lineTo(29.25f, 35.17f)
            lineTo(15.75f, 35.17f)
            lineTo(18.45f, 27.97f)
            lineTo(17.1f, 16.27f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFFFFFFFF)), strokeLineWidth = 3.06f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(22.5f, 8.17f)
            lineTo(27.9f, 16.27f)
            lineTo(26.55f, 27.97f)
            lineTo(29.25f, 35.17f)
            lineTo(15.75f, 35.17f)
            lineTo(18.45f, 27.97f)
            lineTo(17.1f, 16.27f)
            close()
        }
        path(fill = null, stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 2.16f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.NonZero) {
            moveTo(24.75f, 15.82f)
            lineTo(20.7f, 21.22f)
        }
    }

    private fun whiteRook(): ImageVector = piece("WHITE_ROOK") {
        // wR.svg
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 7.06f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(13.05f, 35.17f)
            lineTo(13.05f, 12.67f)
            lineTo(15.45f, 12.67f)
            lineTo(15.45f, 17.17f)
            lineTo(21.3f, 17.17f)
            lineTo(21.3f, 12.67f)
            lineTo(23.7f, 12.67f)
            lineTo(23.7f, 17.17f)
            lineTo(29.55f, 17.17f)
            lineTo(29.55f, 12.67f)
            lineTo(31.95f, 12.67f)
            lineTo(31.95f, 35.17f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFFFFFFFF)), strokeLineWidth = 3.06f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(13.05f, 35.17f)
            lineTo(13.05f, 12.67f)
            lineTo(15.45f, 12.67f)
            lineTo(15.45f, 17.17f)
            lineTo(21.3f, 17.17f)
            lineTo(21.3f, 12.67f)
            lineTo(23.7f, 12.67f)
            lineTo(23.7f, 17.17f)
            lineTo(29.55f, 17.17f)
            lineTo(29.55f, 12.67f)
            lineTo(31.95f, 12.67f)
            lineTo(31.95f, 35.17f)
            close()
        }
    }

    private fun whiteQueen(): ImageVector = piece("WHITE_QUEEN") {
        // wQ.svg
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 7.06f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(15.3f, 35.17f)
            lineTo(12.6f, 10.87f)
            lineTo(18.45f, 24.37f)
            lineTo(22.5f, 8.62f)
            lineTo(26.55f, 24.37f)
            lineTo(32.4f, 10.87f)
            lineTo(29.7f, 35.17f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFFFFFFFF)), strokeLineWidth = 3.06f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(15.3f, 35.17f)
            lineTo(12.6f, 10.87f)
            lineTo(18.45f, 24.37f)
            lineTo(22.5f, 8.62f)
            lineTo(26.55f, 24.37f)
            lineTo(32.4f, 10.87f)
            lineTo(29.7f, 35.17f)
            close()
        }
    }

    private fun whiteKing(): ImageVector = piece("WHITE_KING") {
        // wK.svg
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 7.06f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(14.4f, 35.17f)
            lineTo(15.75f, 17.62f)
            lineTo(29.25f, 17.62f)
            lineTo(30.6f, 35.17f)
            close()
        }
        path(fill = null, stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 7.06f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.NonZero) {
            moveTo(22.5f, 2.32f)
            lineTo(22.5f, 17.62f)
        }
        path(fill = null, stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 7.06f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.NonZero) {
            moveTo(14.85f, 8.62f)
            lineTo(30.15f, 8.62f)
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = SolidColor(Color(0xFFFFFFFF)), strokeLineWidth = 3.06f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(14.4f, 35.17f)
            lineTo(15.75f, 17.62f)
            lineTo(29.25f, 17.62f)
            lineTo(30.6f, 35.17f)
            close()
        }
        path(fill = null, stroke = SolidColor(Color(0xFFFFFFFF)), strokeLineWidth = 3.06f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.NonZero) {
            moveTo(22.5f, 4.12f)
            lineTo(22.5f, 17.62f)
        }
        path(fill = null, stroke = SolidColor(Color(0xFFFFFFFF)), strokeLineWidth = 3.06f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.NonZero) {
            moveTo(16.65f, 8.62f)
            lineTo(28.35f, 8.62f)
        }
    }

    private fun blackPawn(): ImageVector = piece("BLACK_PAWN") {
        // bP.svg
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 3.4f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(19f, 22.87f)
            curveTo(16.884f, 21.35f, 15.99f, 18.638f, 16.789f, 16.158f)
            curveTo(17.587f, 13.678f, 19.895f, 11.997f, 22.5f, 11.997f)
            curveTo(25.105f, 11.997f, 27.413f, 13.678f, 28.211f, 16.158f)
            curveTo(29.01f, 18.638f, 28.116f, 21.35f, 26f, 22.87f)
            lineTo(31.5f, 37f)
            lineTo(13.5f, 37f)
            close()
        }
    }

    private fun blackKnight(): ImageVector = piece("BLACK_KNIGHT") {
        // bN.svg
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 3.4f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(15f, 37f)
            lineTo(19.5f, 27f)
            lineTo(11f, 24.5f)
            lineTo(12f, 18f)
            lineTo(19.5f, 10.5f)
            lineTo(21f, 5.5f)
            lineTo(25f, 9.5f)
            lineTo(30.5f, 14.5f)
            lineTo(32.5f, 23f)
            lineTo(32.5f, 37f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFFFFF)), stroke = null, strokeLineWidth = 1f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.NonZero) {
            moveTo(17.9f, 16f)
            curveTo(17.9f, 16.884f, 18.616f, 17.6f, 19.5f, 17.6f)
            curveTo(20.384f, 17.6f, 21.1f, 16.884f, 21.1f, 16f)
            curveTo(21.1f, 15.116f, 20.384f, 14.4f, 19.5f, 14.4f)
            curveTo(18.616f, 14.4f, 17.9f, 15.116f, 17.9f, 16f)
            close()
        }
    }

    private fun blackBishop(): ImageVector = piece("BLACK_BISHOP") {
        // bB.svg
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 3.4f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(22.5f, 7f)
            lineTo(28.5f, 16f)
            lineTo(27f, 29f)
            lineTo(30f, 37f)
            lineTo(15f, 37f)
            lineTo(18f, 29f)
            lineTo(16.5f, 16f)
            close()
        }
        path(fill = null, stroke = SolidColor(Color(0xFFFFFFFF)), strokeLineWidth = 2.4f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.NonZero) {
            moveTo(25f, 15.5f)
            lineTo(20.5f, 21.5f)
        }
    }

    private fun blackRook(): ImageVector = piece("BLACK_ROOK") {
        // bR.svg
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 3.4f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(12f, 37f)
            lineTo(12f, 12f)
            lineTo(14.67f, 12f)
            lineTo(14.67f, 17f)
            lineTo(21.17f, 17f)
            lineTo(21.17f, 12f)
            lineTo(23.83f, 12f)
            lineTo(23.83f, 17f)
            lineTo(30.33f, 17f)
            lineTo(30.33f, 12f)
            lineTo(33f, 12f)
            lineTo(33f, 37f)
            close()
        }
    }

    private fun blackQueen(): ImageVector = piece("BLACK_QUEEN") {
        // bQ.svg
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 3.4f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(14.5f, 37f)
            lineTo(11.5f, 10f)
            lineTo(18f, 25f)
            lineTo(22.5f, 7.5f)
            lineTo(27f, 25f)
            lineTo(33.5f, 10f)
            lineTo(30.5f, 37f)
            close()
        }
    }

    private fun blackKing(): ImageVector = piece("BLACK_KING") {
        // bK.svg
        path(fill = SolidColor(Color(0xFF000000)), stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 3.4f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Round, pathFillType = PathFillType.NonZero) {
            moveTo(13.5f, 37f)
            lineTo(15f, 17.5f)
            lineTo(30f, 17.5f)
            lineTo(31.5f, 37f)
            close()
        }
        path(fill = null, stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 3.4f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.NonZero) {
            moveTo(22.5f, 2.5f)
            lineTo(22.5f, 17.5f)
        }
        path(fill = null, stroke = SolidColor(Color(0xFF000000)), strokeLineWidth = 3.4f, strokeLineCap = StrokeCap.Butt, strokeLineJoin = StrokeJoin.Miter, pathFillType = PathFillType.NonZero) {
            moveTo(16f, 7.5f)
            lineTo(29f, 7.5f)
        }
    }
}
