#!/usr/bin/env bash
# Generates the rules core's Polyglot Random64 table from the Polyglot book-format specification,
# so none of its 781 constants is typed by hand (docs/book.md).
#
#   scripts/polyglot-random64.sh           rewrite tool/.../rules/PolyglotRandom64.kt from the spec
#   scripts/polyglot-random64.sh --check   fail if the committed file differs from the spec
set -euo pipefail

SPEC_URL="https://hgm.nubati.net/book_format.html"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/tool/src/main/kotlin/com/yarosz/chess/rules/PolyglotRandom64.kt"

html="$(curl -sSfL "$SPEC_URL")"
values="$(printf '%s\n' "$html" | grep -o 'U64(0x[0-9A-Fa-f]\{16\})' | sed 's/U64(0x\(.*\))/\1/')"
count="$(printf '%s\n' "$values" | wc -l | tr -d ' ')"
if [ "$count" != 781 ]; then
  echo "polyglot-random64: expected 781 constants in $SPEC_URL, found $count" >&2
  exit 1
fi

generate() {
  cat <<HEAD
// Generated by scripts/polyglot-random64.sh from the Polyglot book-format specification,
// $SPEC_URL (the array Random64[781]). Do not edit by hand.
// Offsets: pieces 0-767, castling 768-771, en passant file 772-779, White to move 780.
package com.yarosz.chess.rules

internal val POLYGLOT_RANDOM64: LongArray = longArrayOf(
HEAD
  printf '%s\n' "$values" | awk '{ printf "%s0x%suL.toLong(),", (NR % 4 == 1 ? "    " : " "), toupper($0); if (NR % 4 == 0) printf "\n" } END { if (NR % 4 != 0) printf "\n" }'
  echo ")"
}

if [ "${1:-}" = "--check" ]; then
  if diff -u "$OUT" <(generate) >/dev/null; then
    echo "polyglot-random64: OK (781 constants match $SPEC_URL)"
  else
    echo "polyglot-random64: FAIL $OUT differs from $SPEC_URL; run scripts/polyglot-random64.sh" >&2
    exit 1
  fi
else
  generate > "$OUT"
  echo "polyglot-random64: wrote ${OUT#"$ROOT"/}"
fi
