/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b2768128f5b2f27fc549073b8055b0e3)
interface __BaseEnv_Env {
	REDEEM_LIMITER: RateLimit;
	GAME: DurableObjectNamespace<import("./src/index").CorrespondenceGame>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "CorrespondenceGame";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
