/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 7ad209b8275b0b68753d2058e353d918)
interface __BaseEnv_Env {
	REDEEM_LIMITER: RateLimit;
	CREATE_LIMITER: RateLimit;
	REDEEM_WIDE_LIMITER: RateLimit;
	CREATE_WIDE_LIMITER: RateLimit;
	GAME: DurableObjectNamespace<import("./src/index").CorrespondenceGame>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "CorrespondenceGame";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
