/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 6888c812eafb3eae1166e83c09d46459)
interface __BaseEnv_Env {
	REDEEM_LIMITER: RateLimit;
	CREATE_LIMITER: RateLimit;
	GAME: DurableObjectNamespace<import("./src/index").CorrespondenceGame>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "CorrespondenceGame";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
